name: Create artifact

on:
  workflow_dispatch:
  push:
    branches: 'main'
    paths: ['**', '!.github/**', '.github/workflows/package-artifact.yml']

permissions:
  contents: write

jobs:
  package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Create smt-scope zip
        run: |
          zip -r smt-scope.zip smt-scope/* -x **/.git -x **/smt-logs

      - name: Upload artifact files
        uses: softprops/action-gh-release@v1
        with:
          tag_name: latest
          files: |
            smt-scope.zip
            LICENSE
            README.md
